### ISSUE TITLE
Exclude columns generates empty DIV´s

### ISSUE THREAD

**Issue by alex84G** [cyberhobo/ColumnFilterWidgets#19] opened 2013-01-15 13:25 UTC
The exclude columns option generates empty DIV´s. Therefore the space between the individual drop down menus increases:

<div class="column-filter-widget"></div>

<div class="column-filter-widget"></div>

<div class="column-filter-widget"></div>

**Comment by cyberhobo** [comment] 2013-01-15 14:26
Duplicate of #13, I think. I'll bump the version to 1.0.3 and tag to include that fix.

**Closed as completed by cyberhobo** 2013-01-15 14:26 UTC
